services:
  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - '6379:6379'
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - redis-data:/data
  yjs:
    image: alokinplc/y-websocket
    container_name: yjs-server
    ports:
      - '6000:6000'
    environment:
      - PORT=6000

volumes:
  redis-data:
